### PR TITLE
fix: Remove trailing whitespace character when exporting My List - Closes #4

### LINKED ISSUE #4: Remove trailing whitespace character when exporting My List
Is it possible to [trim](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim) the entries when exporting My List?
I'm version tracking My List and currently it's placing a trailing space character at the end of each line.

Partial output of `git diff --color-moved=plain --cached`:

git-diff-output

Not sure if exporting ThumbsUp and ThumbsDown lists exhibit the same behaviour as they have remained unchanged for me between commits so far, but it's worth investigating them too.

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
Hi, this commit should fix issue #4. The trailing spaces should be removed from the exported list. Please let me know if there is anything I can improve, thank you.

### CODE REVIEW

**Comment by daltonmenezes** [comment]
Hi @yuanLeeMidori thanks for the PRs. I'm testing and trying to figure out if this new blank line spaces are expected by you.

screenshot

**Comment by yuanLeeMidori** [comment]
Thank you for reviewing my code. No, it is not expected. I've tested this `issue-4` branch again but didn't see the new line in the first line. In the PR, I only remove the whitespace right after the TV-show/movie name, it shouldn't bring a new line in the very first line. 

Please let me know if the issue is still there in my PR, thank you.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori  I'm going to merge this one, but the issue was in the #6 PR, so I reverted that merge. Can you check the #6 please?

**Comment by yuanLeeMidori** [comment]
Sure. I'll send a new PR for solving issue #5 with no new line in the beginning. Thank you for pointing it out.

**Pull request merged**
