### PR TITLE
fix: sort the exported list (fix new line issue)

### LINKED ISSUE #5: sort My List export output
Is it possible to implement sorting of My List output?
If possible, make a settings page for the extension so that we can customize sort behaviour to our own preference.
Sort option examples could include "as-is" or alphabetically.

The primary use case would be for those of us that version track the output,
to avoid having the lines move around between commits.

Of course, those inclined to solve this on our own can easily do it by running (on Linux):
`cat output.txt | sort >> tracked-mylist-file.txt`

But I'm hoping this can be natively supported by the plugin?

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
Hi, since PR #6 has been closed, I create this new PR for solving issue #5 with no new line in the very beginning. Thank you again for reviewing and testing my code.

### CODE REVIEW

**Comment by daltonmenezes** [comment]
@yuanLeeMidori Thank you, can you resolve the conflicts between this PR and the updated branch master with your previous PR?

**Comment by yuanLeeMidori** [comment]
Just reloved the conflicts. They should be good to merge. Let me know if there's anything I can do, thank you!

**Comment by daltonmenezes** [comment]
@yuanLeeMidori Thanks, it's almost perfect, I'm just wondering about the letters with accent. Can you improve the .sort() function to put for example, the **A** and **À** together before the next letter (B)?

This is the the current state:
```
A Babá
A Bruxa
A Casa de Cera
A Maldição da Mansão Bl
Bird Box
Watchmen - O filme
Would You Rather
Wynonna Earp
Zumbilândia
[REC]
À Espera de um milagreQuestão de Tempo
À Procura da Felicidade
À Prova de Morte
À Sombra do Medo
À Sombra do MedoPsicoseKung FuryUm drink no inferno
```
And it would be great if we got the following result:
```
A Babá
A Bruxa
A Casa de Cera
A Maldição da Mansão Bl
À Espera de um milagreQuestão de Tempo
À Procura da Felicidade
À Prova de Morte
À Sombra do Medo
À Sombra do MedoPsicoseKung FuryUm drink no inferno
Bird Box
Watchmen - O filme
Would You Rather
Wynonna Earp
Zumbilândia
[REC]
```
Or
```
À Espera de um milagreQuestão de Tempo
À Procura da Felicidade
À Prova de Morte
À Sombra do Medo
À Sombra do MedoPsicoseKung FuryUm drink no inferno
A Babá
A Bruxa
A Casa de Cera
A Maldição da Mansão Bl
Bird Box
Watchmen - O filme
Would You Rather
Wynonna Earp
Zumbilândia
[REC]
```

What do you think about it?

**Comment by daltonmenezes** [comment]
@yuanLeeMidori I believe this
```js
.sort(Intl.Collator().compare)
```
resolves my previous point. Can you try it and update the sorts in the code with it please?

**Comment by yuanLeeMidori** [comment]
Sorry I was sleeping. I've updated all `sort()` with `Intl.Collator().compare`.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori Thanks. For some reason, the last items in the list are copied on the same line, like this

> Would You Rather
> Wynonna Earp
> Z Nation
> **ZumbilândiaQuestão de TempoPsicoseKung FuryUm drink no inferno**

where the result should be

> Would You Rather
> Wynonna Earp
> Z Nation
> **Zumbilândia**
> **Questão de Tempo**
> **Psicose**
> **Kung Fury**
> **Um drink no inferno**

Can you check it please?

**Comment by daltonmenezes** [comment]
@yuanLeeMidori my previous point can be fixed by doing this:
```js
.then(data => {
      if (data.ratingItems.length > 0) {
          data.ratingItems.map(data =>
            rate[thumb](data) 
              ? list += '\n' + data.title + '\n' 
              : ''
          )
          currentPageNumber++
          list = [...new Set(list.split('\n').filter(Boolean))].sort(Intl.Collator().compare).join('\n')
          return thumbsListCreator(thumb, list, currentPageNumber)
      }
      return list
    })
```
The "Set" is to remove duplicated names. Try it and update the code please, also it would be great to make the code more consistent if you remove the semicolons and change the double quotes to single quotes. In a near future I'll put eslint/prettier to make our life more easier about it :D

**Comment by yuanLeeMidori** [comment]
Hi, I've updated them with the `new Set` to prevent the duplicate issue and change the coding style as well, thanks for the reminder. 

However, since I don't know the Portuguese language, it is a bit hard for me to get the Portuguese TVShow/movie names and test the functionalities. I've tried to change the language setting but couldn't get the list as you show to test. Moreover, even if there are multiple names being copied on the same line, I can't quite tell it because I can't read the language. 

Anyways, please let me know if there is anything I can do, thank you.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori No problem, thanks. But you forgot the
```js
 list += '\n' + data.title + '\n' 
```
If you don't put that new line at the beginning, the result still keep that [issue](https://github.com/daltonmenezes/netflix-list-exporter/pull/9#issuecomment-719644472)

**Comment by yuanLeeMidori** [comment]
` list += '\n' + data.title + '\n' ` is for the thumbs-list-creator? If it is, there wasn't a new line before I sent my PRs. Would you like me to add them? Not sure if I get what you mean.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori You right, the point is: to your updates works properly and resolve that [issue](https://github.com/daltonmenezes/netflix-list-exporter/pull/9#issuecomment-719644472), you have to add this new line in the beginning, otherwise it will not work.

Just update `thumbs-list-creator.js` files from this
```js
 list += data.title + '\n' 
```
to this
```js
 list += '\n' + data.title + '\n' 
```

**Comment by yuanLeeMidori** [comment]
The `my-list-creator.js` or `thumbs-list-creator.js`? There is no `data.title` in `my-list-creator.js`.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori I just typed the wrong file name, my apologies. The correct files are the **thumbs-list-creator.js** files

**Comment by yuanLeeMidori** [comment]
No worries. I've tested again and updated them as you suggested. Thank you. Please let me know if there's anything I can do.

**Comment by daltonmenezes** [comment]
@yuanLeeMidori Now it's perfect. Works like a charm on Chrome,Firefox and Opera. Thank you so much for your contributions. As soon as possible I'll release theses updates to the stores.

**Comment by yuanLeeMidori** [comment]
No problem. Thank you for giving me the chance to contribute and help me improve my code. Looking forward to seeing the new version of the extension in the stores!

**Pull request merged**
